sprint4: to ts
trishinanton/react-burger pull request #5
Opened 2024-12-03 12:07 UTC by trishinanton

2024-12-03 17:00 UTC, kyzinatra commented on src/api/resources/user.resourse.ts
> +export const postLogin = (body: Record<string, unknown>) =>
Надо исправить: стоит прописать явные интерфейсы для всех запросов, а не такие общие

2024-12-03 17:02 UTC, kyzinatra commented on src/components/ModalOverlay/index.tsx
> +  // @ts-expect-error
Надо исправить: необходимо назначить правильный типа. Для этого можно посмотреть какой тип принимает метод или функция, если навести на его мышкой и нажать `Crtl + ЛКМ`

2024-12-03 17:04 UTC, kyzinatra commented on src/hooks/useFormData.ts
> +export const useFormData = (inputValues = {}) => {
Надо исправить: так как это общий хук, стоит типизировать его с помощью дженерика

`function <T extends Record<string, string>>(values: T)`

2024-12-03 17:04 UTC, kyzinatra commented on src/pages/Profile/index.tsx
> +  const onChangeEmail = useCallback((e: ChangeEvent<HTMLInputElement>) => {
Отлично! Хорошая типизация событий

2024-12-03 17:05 UTC, kyzinatra requested changes
Отличная работа над типами. Стоит немного еще поработать над тем, чтобы все типы более конкретно описывали те сущности в которыми вы работаете и ваша работа будет принята!

2024-12-04 07:21 UTC, trishinanton commented on src/api/resources/user.resourse.ts
> +export const postLogin = (body: Record<string, unknown>) =>
fix

2024-12-04 07:21 UTC, trishinanton commented on src/components/ModalOverlay/index.tsx
> +  // @ts-expect-error
fix

2024-12-04 07:21 UTC, trishinanton commented on src/hooks/useFormData.ts
> +export const useFormData = (inputValues = {}) => {
fix

2024-12-04 13:09 UTC, kyzinatra commented on src/api/resources/user.resourse.ts
> +  resource<T>({
Можно лучше: лучше, но postRegister принимает вполне конкретный body для конкретного запроса. Этот конкретные тип и стоит тут описать. А в `resource` уже да, обищий тип

2024-12-04 13:10 UTC, kyzinatra commented on src/pages/SignIn/index.tsx
> +      dispatch(fetchLogin<ILogin>(values))
Можно просто не передавать этот тип как дженерик, а сразу явно его прописать для `fetchLogin`

2024-12-04 13:11 UTC, kyzinatra approved these changes
Вы отлично потрудились.
Поздравляю! Ваша работа принята.
Удачного дальнейшего обучения.

2024-12-05 07:54 UTC, merged